### ISSUE TITLE
android - js 编译失败

### ISSUE THREAD

**Issue by tinybearc** [sdkbox/sdkbox-sample-sdkboxads#5]
### sdkboxads 版本： 2.3.3.1

编译出错

~~~
 [dx] associated EnclosingMethod attribute. This class was probably produced by a
       [dx] compiler that did not target the modern .class file format. The recommended
       [dx] solution is to recompile the class from source, using an up-to-date compiler
       [dx] and without specifying any "-target" type options. The consequence of ignoring
       [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
       [dx] warning: Ignoring InnerClasses attribute for an anonymous inner class
       [dx] (com.fyber.c.d.f) that doesn't come with an
       [dx] associated EnclosingMethod attribute. This class was probably produced by a
       [dx] compiler that did not target the modern .class file format. The recommended
       [dx] solution is to recompile the class from source, using an up-to-date compiler
       [dx] and without specifying any "-target" type options. The consequence of ignoring
       [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
       [dx] warning: Ignoring InnerClasses attribute for an anonymous inner class
       [dx] (com.fyber.c.d.g) that doesn't come with an
       [dx] associated EnclosingMethod attribute. This class was probably produced by a
       [dx] compiler that did not target the modern .class file format. The recommended
       [dx] solution is to recompile the class from source, using an up-to-date compiler
       [dx] and without specifying any "-target" type options. The consequence of ignoring
       [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
       [dx] warning: Ignoring InnerClasses attribute for an anonymous inner class
       [dx] (com.fyber.c.d.h) that doesn't come with an
       [dx] associated EnclosingMethod attribute. This class was probably produced by a
       [dx] compiler that did not target the modern .class file format. The recommended
       [dx] solution is to recompile the class from source, using an up-to-date compiler
       [dx] and without specifying any "-target" type options. The consequence of ignoring
       [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
       [dx] warning: Ignoring InnerClasses attribute for an anonymous inner class
       [dx] (com.fyber.c.d.i) that doesn't come with an
       [dx] associated EnclosingMethod attribute. This class was probably produced by a
       [dx] compiler that did not target the modern .class file format. The recommended
       [dx] solution is to recompile the class from source, using an up-to-date compiler
       [dx] and without specifying any "-target" type options. The consequence of ignoring
       [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
       [dx] warning: Ignoring InnerClasses attribute for an anonymous inner class
       [dx] (com.fyber.c.d.j) that doesn't come with an
       [dx] associated EnclosingMethod attribute. This class was probably produced by a
       [dx] compiler that did not target the modern .class file format. The recommended
       [dx] solution is to recompile the class from source, using an up-to-date compiler
       [dx] and without specifying any "-target" type options. The consequence of ignoring
       [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
       [dx] warning: Ignoring InnerClasses attribute for an anonymous inner class
       [dx] (com.fyber.c.d.k) that doesn't come with an
       [dx] associated EnclosingMethod attribute. This class was probably produced by a
       [dx] compiler that did not target the modern .class file format. The recommended
       [dx] solution is to recompile the class from source, using an up-to-date compiler
       [dx] and without specifying any "-target" type options. The consequence of ignoring
       [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
      [dex] Pre-Dexing /Users/xqc/Documents/sample/sdkbox-sample-sdkboxads/js/frameworks/runtime-src/proj.android/libs/httpcore-4.4.4.jar -> httpcore-4.4.4-1770ff23737572f7322cb50cc2c2f078.jar
      [dex] Pre-Dexing /Users/xqc/Documents/sample/sdkbox-sample-sdkboxads/js/frameworks/runtime-src/proj.android/libs/vungle-publisher-adaptive-id-3.3.5.jar -> vungle-publisher-adaptive-id-3.3.5-2313fdea0c61e468d6489ba541198095.jar
      [dex] Pre-Dexing /Users/xqc/Documents/sample/sdkbox-sample-sdkboxads/js/frameworks/runtime-src/proj.android/libs/chartboost.jar -> chartboost-a2597b9c96d48d9ff689ddc696e27d4c.jar
      [dex] Converting compiled files and external libraries into /Users/xqc/Documents/sample/sdkbox-sample-sdkboxads/js/frameworks/runtime-src/proj.android/bin/classes.dex...
       [dx] Merged dex A (144 defs/152.0KiB) with dex B (1 defs/0.4KiB). Result is 145 defs/179.9KiB. Took 0.2s
       [dx] Merged dex A (145 defs/179.9KiB) with dex B (15 defs/18.9KiB). Result is 160 defs/247.3KiB. Took 0.1s
       [dx] Merged dex A (160 defs/247.3KiB) with dex B (20 defs/25.8KiB). Result is 180 defs/359.9KiB. Took 0.1s
       [dx] Merged dex A (180 defs/359.9KiB) with dex B (416 defs/238.7KiB). Result is 596 defs/796.5KiB. Took 0.1s
       [dx] Merged dex A (596 defs/796.5KiB) with dex B (18 defs/22.4KiB). Result is 614 defs/1178.2KiB. Took 0.1s
       [dx] Result compacted from 3037.4KiB to 1392.5KiB to save 1644.9KiB
       [dx] Merged dex A (614 defs/1178.2KiB) with dex B (943 defs/967.7KiB). Result is 1557 defs/1392.5KiB. Took 0.4s
       [dx] Merged dex A (1557 defs/1392.5KiB) with dex B (73 defs/100.8KiB). Result is 1630 defs/1823.3KiB. Took 0.2s
       [dx] Result compacted from 6661.2KiB to 5118.4KiB to save 1542.8KiB
       [dx] Merged dex A (1630 defs/1823.3KiB) with dex B (4466 defs/3654.9KiB). Result is 6096 defs/5118.4KiB. Took 1.0s
       [dx] Result compacted from 6369.4KiB to 5300.3KiB to save 1069.2KiB
       [dx] Merged dex A (6096 defs/5118.4KiB) with dex B (92 defs/202.6KiB). Result is 6188 defs/5300.3KiB. Took 0.7s
       [dx] Result compacted from 6445.6KiB to 5364.9KiB to save 1080.6KiB
       [dx] Merged dex A (6188 defs/5300.3KiB) with dex B (77 defs/80.0KiB). Result is 6265 defs/5364.9KiB. Took 0.6s
       [dx] Result compacted from 6465.9KiB to 5391.2KiB to save 1074.7KiB
       [dx] Merged dex A (6265 defs/5364.9KiB) with dex B (45 defs/29.6KiB). Result is 6310 defs/5391.2KiB. Took 0.5s
       [dx] Result compacted from 6479.4KiB to 5402.1KiB to save 1077.3KiB
       [dx] 
       [dx] UNEXPECTED TOP-LEVEL EXCEPTION:
       [dx] com.android.dex.DexException: Multiple dex files define Lorg/apache/http/auth/AUTH;
       [dx] 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
       [dx] 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
       [dx] 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
       [dx] 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
       [dx] 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
       [dx] 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
       [dx] 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
       [dx] Merged dex A (6310 defs/5391.2KiB) with dex B (17 defs/14.4KiB). Result is 6327 defs/5402.1KiB. Took 0.6s
       [dx] 	at com.android.dx.command.dexer.Main.run(Main.java:277)
       [dx] 	at com.android.dx.command.dexer.Main.main(Main.java:245)
       [dx] 	at com.android.dx.command.Main.main(Main.java:106)
       [dx] 

BUILD FAILED
/Users/xqc/Android/android-sdk/tools/ant/build.xml:888: The following error occurred while executing this line:
/Users/xqc/Android/android-sdk/tools/ant/build.xml:890: The following error occurred while executing this line:
/Users/xqc/Android/android-sdk/tools/ant/build.xml:902: The following error occurred while executing this line:
/Users/xqc/Android/android-sdk/tools/ant/build.xml:283: null returned: 2

Total time: 1 minute 59 seconds
执行命令出错，返回值：1。
~~~

**Comment by hugohuang1111** [comment]
fixed, please test agagin
