### ISSUE TITLE
android - cpp 编译失败

### ISSUE THREAD

**Issue by tinybearc** [sdkbox/sdkbox-sample-sdkboxads#6]
### sdkboxads 版本： 2.3.3.1

编译失败

~~~
[dx] and without specifying any "-target" type options. The consequence of ignoring
       [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
       [dx] warning: Ignoring InnerClasses attribute for an anonymous inner class
       [dx] (com.fyber.c.d.j) that doesn't come with an
       [dx] associated EnclosingMethod attribute. This class was probably produced by a
       [dx] compiler that did not target the modern .class file format. The recommended
       [dx] solution is to recompile the class from source, using an up-to-date compiler
       [dx] and without specifying any "-target" type options. The consequence of ignoring
       [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
      [dex] Pre-Dexing /Users/xqc/Documents/sample/sdkbox-sample-sdkboxads/cpp/proj.android/libs/httpcore-4.4.4.jar -> httpcore-4.4.4-58fa44000f5e0a82c9191c5e9f21e37d.jar
      [dex] Pre-Dexing /Users/xqc/Documents/sample/sdkbox-sample-sdkboxads/cpp/proj.android/libs/vungle-publisher-adaptive-id-3.3.5.jar -> vungle-publisher-adaptive-id-3.3.5-b3a575d74f4ae77dcbb28020f6c4a46f.jar
      [dex] Pre-Dexing /Users/xqc/Documents/sample/sdkbox-sample-sdkboxads/cpp/proj.android/libs/chartboost.jar -> chartboost-c29113af71817448aea68b233e1cbde8.jar
      [dex] Converting compiled files and external libraries into /Users/xqc/Documents/sample/sdkbox-sample-sdkboxads/cpp/proj.android/bin/classes.dex...
       [dx] Merged dex A (144 defs/151.1KiB) with dex B (1 defs/0.4KiB). Result is 145 defs/178.8KiB. Took 0.2s
       [dx] Merged dex A (145 defs/178.8KiB) with dex B (15 defs/18.9KiB). Result is 160 defs/246.0KiB. Took 0.1s
       [dx] Merged dex A (160 defs/246.0KiB) with dex B (20 defs/25.8KiB). Result is 180 defs/358.2KiB. Took 0.1s
       [dx] Merged dex A (180 defs/358.2KiB) with dex B (416 defs/238.7KiB). Result is 596 defs/794.1KiB. Took 0.1s
       [dx] Merged dex A (596 defs/794.1KiB) with dex B (18 defs/22.4KiB). Result is 614 defs/1174.5KiB. Took 0.1s
       [dx] Result compacted from 3031.5KiB to 1391.7KiB to save 1639.8KiB
       [dx] Merged dex A (614 defs/1174.5KiB) with dex B (943 defs/967.7KiB). Result is 1557 defs/1391.7KiB. Took 0.4s
       [dx] Merged dex A (1557 defs/1391.7KiB) with dex B (73 defs/100.8KiB). Result is 1630 defs/1822.3KiB. Took 0.2s
       [dx] Result compacted from 6660.0KiB to 5117.6KiB to save 1542.4KiB
       [dx] Merged dex A (1630 defs/1822.3KiB) with dex B (4466 defs/3654.9KiB). Result is 6096 defs/5117.6KiB. Took 1.0s
       [dx] Result compacted from 6368.4KiB to 5299.4KiB to save 1069.0KiB
       [dx] Merged dex A (6096 defs/5117.6KiB) with dex B (92 defs/202.6KiB). Result is 6188 defs/5299.4KiB. Took 0.7s
       [dx] Result compacted from 6444.5KiB to 5364.2KiB to save 1080.3KiB
       [dx] Merged dex A (6188 defs/5299.4KiB) with dex B (77 defs/80.0KiB). Result is 6265 defs/5364.2KiB. Took 0.6s
       [dx] Result compacted from 6465.0KiB to 5390.4KiB to save 1074.6KiB
       [dx] Merged dex A (6265 defs/5364.2KiB) with dex B (45 defs/29.6KiB). Result is 6310 defs/5390.4KiB. Took 0.5s
       [dx] Result compacted from 6478.5KiB to 5401.4KiB to save 1077.1KiB
       [dx] Merged dex A (6310 defs/5390.4KiB) with dex B (17 defs/14.4KiB). Result is 6327 defs/5401.4KiB. Took 0.5s
       [dx] 
       [dx] UNEXPECTED TOP-LEVEL EXCEPTION:
       [dx] com.android.dex.DexException: Multiple dex files define Lorg/apache/http/auth/AUTH;
       [dx] 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
       [dx] 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
       [dx] 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
       [dx] 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
       [dx] 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
       [dx] 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
       [dx] 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
       [dx] 	at com.android.dx.command.dexer.Main.run(Main.java:277)
       [dx] 	at com.android.dx.command.dexer.Main.main(Main.java:245)
       [dx] 	at com.android.dx.command.Main.main(Main.java:106)
       [dx] 

BUILD FAILED
/Users/xqc/Android/android-sdk/tools/ant/build.xml:888: The following error occurred while executing this line:
/Users/xqc/Android/android-sdk/tools/ant/build.xml:890: The following error occurred while executing this line:
/Users/xqc/Android/android-sdk/tools/ant/build.xml:902: The following error occurred while executing this line:
/Users/xqc/Android/android-sdk/tools/ant/build.xml:283: null returned: 2

Total time: 1 minute 46 seconds
执行命令出错，返回值：1。

~~~

**Comment by hugohuang1111** [comment]
fixed, please test agagin
