### ISSUE TITLE
android - lua 编译失败

### ISSUE THREAD

**Issue by tinybearc** [sdkbox/sdkbox-sample-sdkboxads#7]
### sdkboxads 版本： 2.3.3.1

编译失败

~~~
 [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
       [dx] warning: Ignoring InnerClasses attribute for an anonymous inner class
       [dx] (com.fyber.c.d.f) that doesn't come with an
       [dx] associated EnclosingMethod attribute. This class was probably produced by a
       [dx] compiler that did not target the modern .class file format. The recommended
       [dx] solution is to recompile the class from source, using an up-to-date compiler
       [dx] and without specifying any "-target" type options. The consequence of ignoring
       [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
       [dx] warning: Ignoring InnerClasses attribute for an anonymous inner class
       [dx] (com.fyber.c.d.g) that doesn't come with an
       [dx] associated EnclosingMethod attribute. This class was probably produced by a
       [dx] compiler that did not target the modern .class file format. The recommended
       [dx] solution is to recompile the class from source, using an up-to-date compiler
       [dx] and without specifying any "-target" type options. The consequence of ignoring
       [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
       [dx] warning: Ignoring InnerClasses attribute for an anonymous inner class
       [dx] (com.fyber.c.d.h) that doesn't come with an
       [dx] associated EnclosingMethod attribute. This class was probably produced by a
       [dx] compiler that did not target the modern .class file format. The recommended
       [dx] solution is to recompile the class from source, using an up-to-date compiler
       [dx] and without specifying any "-target" type options. The consequence of ignoring
       [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
       [dx] warning: Ignoring InnerClasses attribute for an anonymous inner class
       [dx] (com.fyber.c.d.k) that doesn't come with an
       [dx] associated EnclosingMethod attribute. This class was probably produced by a
       [dx] compiler that did not target the modern .class file format. The recommended
       [dx] solution is to recompile the class from source, using an up-to-date compiler
       [dx] and without specifying any "-target" type options. The consequence of ignoring
       [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
       [dx] warning: Ignoring InnerClasses attribute for an anonymous inner class
       [dx] (com.fyber.c.d.i) that doesn't come with an
       [dx] associated EnclosingMethod attribute. This class was probably produced by a
       [dx] compiler that did not target the modern .class file format. The recommended
       [dx] solution is to recompile the class from source, using an up-to-date compiler
       [dx] and without specifying any "-target" type options. The consequence of ignoring
       [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
       [dx] warning: Ignoring InnerClasses attribute for an anonymous inner class
       [dx] (com.fyber.c.d.j) that doesn't come with an
       [dx] associated EnclosingMethod attribute. This class was probably produced by a
       [dx] compiler that did not target the modern .class file format. The recommended
       [dx] solution is to recompile the class from source, using an up-to-date compiler
       [dx] and without specifying any "-target" type options. The consequence of ignoring
       [dx] this warning is that reflective operations on this class will incorrectly
       [dx] indicate that it is *not* an inner class.
      [dex] Pre-Dexing /Users/xqc/Documents/sample/sdkbox-sample-sdkboxads/lua/frameworks/runtime-src/proj.android/libs/httpcore-4.4.4.jar -> httpcore-4.4.4-ba925996a4a628c6d7a60f1270bc64ef.jar
      [dex] Pre-Dexing /Users/xqc/Documents/sample/sdkbox-sample-sdkboxads/lua/frameworks/runtime-src/proj.android/libs/vungle-publisher-adaptive-id-3.3.5.jar -> vungle-publisher-adaptive-id-3.3.5-04062cc74213b13d6fd5ef989abb6264.jar
      [dex] Pre-Dexing /Users/xqc/Documents/sample/sdkbox-sample-sdkboxads/lua/frameworks/runtime-src/proj.android/libs/chartboost.jar -> chartboost-b713df8b2914c492019522d22d34c33f.jar
      [dex] Converting compiled files and external libraries into /Users/xqc/Documents/sample/sdkbox-sample-sdkboxads/lua/frameworks/runtime-src/proj.android/bin/classes.dex...
       [dx] Merged dex A (145 defs/153.2KiB) with dex B (1 defs/0.4KiB). Result is 146 defs/181.3KiB. Took 0.2s
       [dx] Merged dex A (146 defs/181.3KiB) with dex B (15 defs/18.9KiB). Result is 161 defs/249.0KiB. Took 0.1s
       [dx] Merged dex A (161 defs/249.0KiB) with dex B (20 defs/25.8KiB). Result is 181 defs/362.1KiB. Took 0.1s
       [dx] Merged dex A (181 defs/362.1KiB) with dex B (416 defs/238.7KiB). Result is 597 defs/799.6KiB. Took 0.1s
       [dx] Merged dex A (597 defs/799.6KiB) with dex B (18 defs/22.4KiB). Result is 615 defs/1182.9KiB. Took 0.1s
       [dx] Result compacted from 3045.5KiB to 1393.4KiB to save 1652.1KiB
       [dx] Merged dex A (615 defs/1182.9KiB) with dex B (943 defs/967.7KiB). Result is 1558 defs/1393.4KiB. Took 0.3s
       [dx] Merged dex A (1558 defs/1393.4KiB) with dex B (73 defs/100.8KiB). Result is 1631 defs/1824.3KiB. Took 0.3s
       [dx] Result compacted from 6662.5KiB to 5119.2KiB to save 1543.3KiB
       [dx] Merged dex A (1631 defs/1824.3KiB) with dex B (4466 defs/3654.9KiB). Result is 6097 defs/5119.2KiB. Took 0.9s
       [dx] Result compacted from 6370.4KiB to 5301.1KiB to save 1069.4KiB
       [dx] Merged dex A (6097 defs/5119.2KiB) with dex B (92 defs/202.6KiB). Result is 6189 defs/5301.1KiB. Took 0.8s
       [dx] Result compacted from 6446.5KiB to 5365.7KiB to save 1080.8KiB
       [dx] Merged dex A (6189 defs/5301.1KiB) with dex B (77 defs/80.0KiB). Result is 6266 defs/5365.7KiB. Took 0.7s
       [dx] Result compacted from 6466.8KiB to 5391.9KiB to save 1074.9KiB
       [dx] Merged dex A (6266 defs/5365.7KiB) with dex B (45 defs/29.6KiB). Result is 6311 defs/5391.9KiB. Took 0.6s
       [dx] Result compacted from 6480.3KiB to 5402.9KiB to save 1077.5KiB
       [dx] Merged dex A (6311 defs/5391.9KiB) with dex B (17 defs/14.4KiB). Result is 6328 defs/5402.9KiB. Took 0.8s
       [dx] 
       [dx] UNEXPECTED TOP-LEVEL EXCEPTION:
       [dx] com.android.dex.DexException: Multiple dex files define Lorg/apache/http/auth/AUTH;
       [dx] 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
       [dx] 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
       [dx] 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
       [dx] 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
       [dx] 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
       [dx] 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
       [dx] 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
       [dx] 	at com.android.dx.command.dexer.Main.run(Main.java:277)
       [dx] 	at com.android.dx.command.dexer.Main.main(Main.java:245)
       [dx] 	at com.android.dx.command.Main.main(Main.java:106)
       [dx] 

BUILD FAILED
/Users/xqc/Android/android-sdk/tools/ant/build.xml:888: The following error occurred while executing this line:
/Users/xqc/Android/android-sdk/tools/ant/build.xml:890: The following error occurred while executing this line:
/Users/xqc/Android/android-sdk/tools/ant/build.xml:902: The following error occurred while executing this line:
/Users/xqc/Android/android-sdk/tools/ant/build.xml:283: null returned: 2

Total time: 1 minute 48 seconds
执行命令出错，返回值：1
~~~

**Comment by hugohuang1111** [comment]
fixed, please test agagin
